apiVersion: v1
kind: Pod
metadata:
  name: ibench-llc
  labels:
    name: ibench-llc
spec:
  containers:
    - image: anakli/ibench:llc
      name: ibench-llc
      command: ["/bin/sh"]
      args: ["-c", "taskset -c 1 ./l3 1200"]
  nodeSelector:
    cca-project-nodetype: "parsec"

