apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-blackscholes
  labels:
    name: pasec-blackscholes
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:blackscholes-native-reduced
        name: parsecblackscholes
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "5.5"
          limits:
            cpu: "6"
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0-5 ./bin/parsecmgmt -a run -p blackscholes -i native -n 6"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"
