apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-canneal
  labels:
    name: pasec-canneal
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:canneal-native-reduced
        name: parseccanneal
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
          limits:
            cpu: "2"
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 2-3 ./bin/parsecmgmt -a run -p canneal -i native -n 2"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
