apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-dedup
  labels:
    name: pasec-dedup
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:dedup-native-reduced
        name: parsecdedup
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/parsecmgmt -a run -p dedup -i native -n 1"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "parsec"
